### ISSUE TITLE
Add floating animation to the Tech Squad logo

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#10]
![image](https://user-images.githubusercontent.com/88646338/155557228-a71ee745-815f-40ee-a76f-d1771098df5c.png)

Visit the (https://gssoc.girlscript.tech/) and see their floating logo on the landing page.
Note: Images are taken only for reference.

**Comment by HarshKumarChoudary** [comment]
Please assign this task to me.

**Comment by ronitblenz** [comment]
Hi, You can start working on the issue from now on, I will assign you on 1st march, then you can create a PR
Because you have much time left

Plz ask us on Discord for more details

**Comment by ronitblenz** [comment]
ronitblenz#6939

Here is my Discord

**Comment by JaynouOliver** [comment]
@HarshKumarChoudary assigned you, go for it!

**Comment by HarshKumarChoudary** [comment]
I created the pull request to fix this issue in #38 .
