### ISSUE TITLE
the cards are not of equal size

### ISSUE THREAD

**Issue by itsAftabAlam** [Tech-Squad-Community/techsquad-community-website#102]
### Description

the cards on home page below the text "Are you ready to grow faster?" are not of equal size. I would like to fix that by making these cards of equal size. please assign this issue to me

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by itsAftabAlam** [comment]
please assign this issue to me

**Comment by ronitblenz** [comment]
Its perfectly sized.. can you show me what is the issue in the website you are seeing.. Send a screenshot too

**Comment by ronitblenz** [comment]
I cant see any problem here

**Comment by itsAftabAlam** [comment]
![issue](https://user-images.githubusercontent.com/88653530/156889844-4ff0ce06-fc16-4ec9-805f-f94712277510.png)
that's what i am talking about @ronitblenz

**Comment by ronitblenz** [comment]
Check the preview...final deployment isnnot yet ready ... Here is the link https://techsquad-community-website-git-fork-19arnab1-9e3e8d-ronitblenz.vercel.app/

**Comment by itsAftabAlam** [comment]
alright
