### ISSUE TITLE
Creating Header & Footer in Upcoming Events Page

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#103]
### Description
**This is under GSSoC'22**

After landing in Upcoming Events Page I think navigating to other pages is an issue which can be resolved by adding header and footer that follow entire website design.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by Daksh-jha** [comment]
I would like to create upcoming events page as the whole page is missing.
I am GSSOC participant, please assign me this issue.

**Comment by Kumar-laxmi** [comment]
I think the page is not missing
Only the header and footer are missing

**Comment by ronitblenz** [comment]
@Kumar-laxmi assigned 🔥
