### ISSUE TITLE
Implementing Animations on Home Page to Enrich User Experience

### ISSUE THREAD

**Issue by Shubham29012001** [Tech-Squad-Community/techsquad-community-website#108]
It would be better if we add some animations on the homepage that will enrich the user experience. I am planning to use AoS for animations. Can you please assign this work to me for GSSoC '22?

**Comment by ronitblenz** [comment]
https://techsquad-community-website-8oz88oyfo-ronitblenz.vercel.app/

View the latest website... What changes can be made... plz explain a bit?

**Comment by Shubham29012001** [comment]
Hey @ronitblenz, we can add fade-in animation on the H1 section, and other animations types on other sections.

**Comment by ronitblenz** [comment]
Yeah, that's, why we dont, need further enhancements for now
You can raise other issues or comment in an issue thread too

For now, I am closing the issue
