### ISSUE TITLE
BUG : Loading animation glitch fix

### ISSUE THREAD

**Issue by ronitblenz** [Tech-Squad-Community/techsquad-community-website#112]
**Describe the bug**
The loading animation has shifted to side and the blue background is visible partly
![Mar-06-2022 15-14-10](https://user-images.githubusercontent.com/91361382/156917810-98ca67ae-b4db-4506-81e7-96ac105f53fa.gif)

**Expected behaviour**
The animation should be at the Center and the blue portion or any part of the page should not appear rather it must be fully white and loading animation in the middle

**Desktop (please complete the following information):**
It is happening in Desktop/Laptop

**Smartphone (please complete the following information):**
Same problem happening in Smartphone
Fix both screen sizes

**Comment by itsAftabAlam** [comment]
hey can you plz give a screenshot of expected behaviour? i would like to fix this

**Comment by ronitblenz** [comment]
You should make the change in every page of the project
![Mar-06-2022 16-20-53](https://user-images.githubusercontent.com/91361382/156919900-91b1b409-a734-4344-8c08-06facf925115.gif)

**Comment by itsAftabAlam** [comment]
ok sure

**Comment by HarshKumarChoudary** [comment]
Please consider me next in the queue, if the issue is not resolved. I'm a GSSOC22 participant. Thanks.

**Comment by ronitblenz** [comment]
Sure @HarshKumarChoudary

**Comment by itsAftabAlam** [comment]
@ronitblenz issue fixed, I had also changed nav bar fonts color as they were light grey and after removing blue portion those were not visible

**Comment by ronitblenz** [comment]
You shouldnt have removed the blue portion...
Just needed to make the loading animation in the center
