### ISSUE TITLE
BUG: Overriding of the Nav Bar on Contact and About Us page

### ISSUE THREAD

**Issue by ronitblenz** [Tech-Squad-Community/techsquad-community-website#113]
**Describe the bug**
The Nav bar is overlapping some content of the Contact and About us page

<img width="1440" alt="Screenshot 2022-03-06 at 3 19 57 PM" src="https://user-images.githubusercontent.com/91361382/156918137-707e8191-8959-46d6-bb83-f30726585b9b.png">

<img width="1440" alt="Screenshot 2022-03-06 at 3 19 38 PM" src="https://user-images.githubusercontent.com/91361382/156918115-4ba96fed-da1b-4b4d-910d-4210e55473dd.png">

## -------------Expected behavior---------------
<img width="1440" alt="Screenshot 2022-03-06 at 3 26 25 PM" src="https://user-images.githubusercontent.com/91361382/156918214-a0c83f23-ce58-4dbe-b436-163460e08d43.png">
<img width="1440" alt="Screenshot 2022-03-06 at 3 26 48 PM" src="https://user-images.githubusercontent.com/91361382/156918216-47b143bd-a4fb-44d4-bfd8-b69719dc47cf.png">

**Screenshots**

**Desktop (please complete the following information):**
It is happening for Desktop/Laptop

**Smartphone (please complete the following information):**
It is happening for Smartphone and Small screen devices as well
Fix both cases

**Comment by itsAftabAlam** [comment]
can i work on this issue? plz assign this to me

**Comment by ronitblenz** [comment]
Assigned ✨

**Comment by itsAftabAlam** [comment]
I hope this fixes the issue @ronitblenz
