### ISSUE TITLE
A Custom Scroll bar for the website

### ISSUE THREAD

**Issue by ronitblenz** [Tech-Squad-Community/techsquad-community-website#114]
### Description

It should match the colour code of our website and if anyone is confused what a scroll bar is, the screen shot is here..

![WhatsApp Image 2022-03-06 at 4 18 52 PM](https://user-images.githubusercontent.com/91361382/156919840-7222c6cd-d894-41d8-afbd-fc7bf5dbb19b.jpeg)

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by Himanshu664** [comment]
I want to work on it , please assign also mention which color is preferred for scrollbar

**Comment by Pranai2518** [comment]
I would like to work on this issue. please assign it to me.

**Comment by ronitblenz** [comment]
@Himanshu664 Assigned 🔥
