### ISSUE TITLE
Add Header and Footer in LogIn page

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#117]
### Description

In LogIn page we can see that their is no Header and Footer which makes navigation difficult to other pages.

![image](https://user-images.githubusercontent.com/76027425/156968264-025bacc3-9fb4-40dc-8bbc-187ef6a89ff7.png)

In above image we can see that the header and footer are missing.

Also apart from this the page is also missing icon near title.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by Kumar-laxmi** [comment]
And along with this I would also do a bit of code optimization on other pages.

**Comment by ahmadjubair33** [comment]
Hi, @Tech-Squad-Community Assign this issue to me I will add a good design header and footer for the login page.

**Comment by ronitblenz** [comment]
Yeah sure go ahead

**Comment by ronitblenz** [comment]
@Kumar-laxmi assigned✨
