### ISSUE TITLE
Enhancement : Making better UI of counting section in about page 

### ISSUE THREAD

**Issue by akki251** [Tech-Squad-Community/techsquad-community-website#118]
### Description

Hi, If anyone is not working on it, Please assign it to me , I would love to beautify it 😊

![image](https://user-images.githubusercontent.com/67007034/156971014-c5f77a01-29ae-48ed-af0d-cec4f990e549.png)

@r3yc0n1c 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by r3yc0n1c** [comment]
great! let's discuss the prototype in the sever

**Comment by akki251** [comment]
Here it is @r3yc0n1c  

![Sample](https://user-images.githubusercontent.com/67007034/156981495-d568917a-c47f-4c14-9f54-51e09d7683d3.png)

**Comment by r3yc0n1c** [comment]
@akki251 also, link the respective cards to the repo
