### ISSUE TITLE
Implement Light and Dark Mode

### ISSUE THREAD

**Issue by ikavyajain** [Tech-Squad-Community/techsquad-community-website#12]
A website should be user-friendly offering both types of modes as per convenience!

**Comment by ronitblenz** [comment]
Yeah sure, you can work on this issue. 
I will assign you on 1st March

**Comment by ronitblenz** [comment]
you are assigned, start working on the issue and create a PR... Good luck

**Comment by Anish1411** [comment]
okk

**Comment by ronitblenz** [comment]
> okk

I assigned @ikavyajain because we assign on a first-come, first-serve basis. If she fails to do it within time, it will be forwarded to you @Anish1411 
For now, you can check for new issues and also you may create one for yourself if you find something necessary to change

**Comment by flow6979** [comment]
if available, I can work on this project. thank you

**Comment by StillAbeginnerr** [comment]
i want to work on this issue if the previous deadline is passed and work is not done.

**Comment by ronitblenz** [comment]
@ikavyajain has made the toggle button.... You have to make the dark mode theme.

Assigned to @StillAbeginnerr

**Comment by StillAbeginnerr** [comment]
Okay, I will submit my work in 5 days as per level 3 deadline

**Comment by ikavyajain** [comment]
Almost work is done you just need to change the theme and some font colors!
Ronit can guide you better through the deadline of submission! Thanks!🥳

**Comment by ronitblenz** [comment]
Yeah sure, the deadline is 3 days... Contact me when you need some help

**Comment by StillAbeginnerr** [comment]
okay @ikavyajain thanks for guiding about the left over tasks and okay @ronitblenz , i will try to complete it before deadline.

**Comment by ronitblenz** [comment]
Sure Team Diversion 🤞

**Comment by StillAbeginnerr** [comment]
Yeah bro 👍👍

**Comment by StillAbeginnerr** [comment]
@ronitblenz i have unassigned myself because my code is not working properly on index.html but working good on other pages.

**Comment by ronitblenz** [comment]
Yeah sure, take care..

**Comment by sohan2503001** [comment]
@ronitblenz i want to work on this issue

**Comment by ronitblenz** [comment]
Cool ... Assigned @sohan2503001

**Comment by Kavya-mothukuri** [comment]
@ronitblenz hey..if he fails to do.please assign it to me

**Comment by ronitblenz** [comment]
@Kavya-mothukuri You are assigned ✨
