### ISSUE TITLE
Fix UI bugs in Login Page

### ISSUE THREAD

**Issue by RaviAnand111** [Tech-Squad-Community/techsquad-community-website#120]
1.The `Not Registered` link does not have enough margin which makes it look weird.
2.The Margin to the logo in the login card is a little much which can be decreased.
3.The box shadow given to email and password looks a little off. 
4.The input and password boxes edges can be decreased to 20 or 30% to make it look a little better.

![image](https://user-images.githubusercontent.com/59113935/157031803-8fd4d5df-9b08-4a5a-8540-f2d84408d4b9.png)

Hey @ronitblenz , all these views are mine, your opinions are welcome, lets work together and try to make techsquad website better. 
If you agree with the issues I mentioned, I would like to work on them. 
Thanks

**Comment by ronitblenz** [comment]
But I thank you for the detailed observations you made and for the time you invested...
🫂
