### ISSUE TITLE
Giving tilt  and rgb effect  to the cards on homepage.

### ISSUE THREAD

**Issue by muizan** [Tech-Squad-Community/techsquad-community-website#124]
### Description

giving cards the same effect  as the animation on the homepage with 3d rgb effect.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Always leave some samples with the issue...
Plz give some

**Comment by muizan** [comment]
![Web capture_9-3-2022_104135_redstapler co](https://user-images.githubusercontent.com/93467099/157377274-2ff3e5a9-73b6-4a15-95b7-f73af0157724.jpeg)

**Comment by ronitblenz** [comment]
This effect is not needed in our website for now
Thanks for your Concern
