### ISSUE TITLE
Create a new Resource Page

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#125]
### Description

I see that the resource page hasn't been made yet, so I can make it!

![image](https://user-images.githubusercontent.com/76027425/157244712-5070fa2b-1e9f-4061-a835-423137a144e5.png)

The above image is sample of what this page may include

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ishika1501** [comment]
@ronitblenz sir , i would like to work over this issue , (designing the resources pages by basic HTML/JS/CSS) could you assign it to me.

**Comment by ronitblenz** [comment]
That template you gave looks good, you can make it like that, and you can add details according to this page I am Providing
Here is the website
https://devohub.vercel.app/

**Comment by Kumar-laxmi** [comment]
Ok

**Comment by Kumar-laxmi** [comment]
Nope resolving glitches

**Comment by Kumar-laxmi** [comment]
![image](https://user-images.githubusercontent.com/76027425/157598569-d15e8891-457d-4308-a0da-945f1925c3c0.png)
 How is this

**Comment by ronitblenz** [comment]
looking great...replace that logos with respective topics....
after solving the glitches send me the final copy before making a PR
