### ISSUE TITLE
Fetch Information of the Repo

### ISSUE THREAD

**Issue by RaviAnand111** [Tech-Squad-Community/techsquad-community-website#126]
### Description

The about section needs live data of the repo like, no. of contributions, no. of issues, no. of pr merged, etc. 
We need to connect our website with the github api to get the required result.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Any Updates?

**Comment by RaviAnand111** [comment]
Yeah, just working on it,

**Comment by HarshKumarChoudary** [comment]
Please consider me in queue if the issue is not resolved. Thanks.

**Comment by ronitblenz** [comment]
@RaviAnand111 Done with the Issue???

**Comment by ronitblenz** [comment]
@RaviAnand111 Plz make a PR, by today
