### ISSUE TITLE
Adding animation on social links

### ISSUE THREAD

**Issue by TG922** [Tech-Squad-Community/techsquad-community-website#129]
### Description

- The social links is looking fine, but adding animation to them adds additional effect to it.
- This feature will help increase User Interface(UI) of your website.
- Please assign me on this issue under GSSOC 22.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Go ahead @TG922

**Comment by ronitblenz** [comment]
Updates??

**Comment by ronitblenz** [comment]
Sure

**Comment by TG922** [comment]
Sorry brother, I have already completed my work.
But I'm waiting for my changes to be added !! Whenever I push my changes to origin. Someone already made a commit 😅😅

So, I fetch changes again and create another branch with changes done.

**Comment by ronitblenz** [comment]
ok

**Comment by TG922** [comment]
Before sending PR today, I want to ask something. Other than Github, LinkedIn is there any other social media account you want to be added to??

As I'm ready to make changes right now!!

**Comment by TG922** [comment]
I recently noticed that your website is responsive.. So now i'm making it responsive is it okay??

Or should I create PR for this right now !!

**Comment by ronitblenz** [comment]
Make it responsive and make a PR

**Comment by ronitblenz** [comment]
Github, Linkedin, Discord ... This is all we need. (Discord link is dead by intention)
