### ISSUE TITLE
Shift the Navigation Bar and Adjust the Logo

### ISSUE THREAD

**Issue by ikavyajain** [Tech-Squad-Community/techsquad-community-website#13]
The logo should be shifted towards the upper left corner and the navigation bar should be shifted a little up!

**Comment by ronitblenz** [comment]
Also adjust the vacant spaces

**Comment by ronitblenz** [comment]
you are assigned, start working on the issue and create a PR... Good luck

**Comment by khushigupta123** [comment]
I am interested in working on this issue, kindly assign this issue to me.
