### ISSUE TITLE
Bring back-to-top arrow in front of the page

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#130]
![image](https://user-images.githubusercontent.com/88646338/158019296-bddff072-a4a9-4018-ae9d-b3264a082e94.png)
Have a look at this image for reference.
Connect with the mentors or Project for further queries.

**Comment by rv602** [comment]
hi @JaynouOliver , Rajagopalan this side.
I am GSSOC 2022 participant.
Kindly assign me this issue.

**Comment by JaynouOliver** [comment]
@rv602 go for it! 
Asigned!

**Comment by ronitblenz** [comment]
Any updates?

**Comment by JaynouOliver** [comment]
Hey, @rv602 Today is your last date to make a PR. If u failed to do so, you will be unassigned

**Comment by ronitblenz** [comment]
I just saw that right now that it is fixed already, I am sorry for this inconvenience. I am closing this issue

**Comment by rv602** [comment]
okay..thank you
