### ISSUE TITLE
Fix the content position in the website.

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#131]
Content should go down when the dropdown button is clicked.
Remove the white spaces! 
![image](https://user-images.githubusercontent.com/88646338/158019529-5b0fb3ff-cb79-49ef-9179-0af0ea022493.png)

**Comment by Pranai2518** [comment]
I would like to work on this issue. Please assign it to me. I'm a GSSoC'22 participant.

**Comment by ronitblenz** [comment]
@Pranai2518 Assigned ✨

**Comment by ronitblenz** [comment]
any Updates??

**Comment by Pranai2518** [comment]
I have exams till tomorrow. I'll start working on it tomorrow. And also can you be more specific on this issue what actually to do.

**Comment by ronitblenz** [comment]
Its well explained, you need to reduce the white space and the content should slide down when the drop down is opened (IN MOBILE VIEW)

**Comment by sohan2503001** [comment]
@ronitblenz i want to work on this , if he is unable to do

**Comment by ronitblenz** [comment]
@sohan2503001 You are assigned ✨

**Comment by sohan2503001** [comment]
Is it okk , Should i make PR

![Screenshot (300)](https://user-images.githubusercontent.com/69068073/159040632-69f3c85b-cda8-4044-b2be-651de9e658cd.png)
![Screenshot (301)](https://user-images.githubusercontent.com/69068073/159040657-5aaafc97-01b1-43da-95ea-ea081fb0d2d7.png)

**Comment by ronitblenz** [comment]
Make a pr lat me check in the deployment
