### ISSUE TITLE
Main picture not visible in the mobile version of the website

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#133]
![image](https://user-images.githubusercontent.com/88646338/158019635-1b4b6f74-d4f6-4f94-8080-ed009d235ada.png)

Have a look at the desktop version of our website and write some code so that the main picture is visible in the mobile version too!

**Comment by sohan2503001** [comment]
Can u assign this issue to me

**Comment by ronitblenz** [comment]
@sohan2503001 Assigned ✨

**Comment by sohan2503001** [comment]
Is it fine, Can I do a PR

![Screenshot (296)](https://user-images.githubusercontent.com/69068073/158056329-6f4289a9-f79a-413d-96e2-dedb8c28ff41.png)
![Screenshot (297)](https://user-images.githubusercontent.com/69068073/158056331-9042e8d6-fb39-4a80-87e9-c97948ffe330.png)
![Screenshot (298)](https://user-images.githubusercontent.com/69068073/158056334-9a8d0cb1-fb81-4519-b35e-2bd6ab006071.png)

**Comment by ronitblenz** [comment]
Cool , Make a Pull Request ✨
