### ISSUE TITLE
Fix footer in the mobile version of the website

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#135]
![image](https://user-images.githubusercontent.com/88646338/158019935-257742b5-a31a-462d-96d0-5e206c889916.png)

Fix the footer of the website. Let me give you an explanation, when we shift to the mobile version of the website, all the links and divs should be center aligned.  Some discussion is required regarding the alignment and other areas, make sure you connect with the mentors or project admin so that you can be guided! 
Thank you!

**Comment by Girlwithasmile** [comment]
I am a contributer at gssoc and would like to work for this

**Comment by ronitblenz** [comment]
@Girlwithasmile Assigned ✨

**Comment by ronitblenz** [comment]
Updates??

**Comment by Girlwithasmile** [comment]
Shall make pr today

**Comment by ronitblenz** [comment]
Cool

**Comment by ronitblenz** [comment]
Where is the PR? Updates? @Girlwithasmile 🥲

**Comment by sohan2503001** [comment]
@ronitblenz I would like to work on this issue

**Comment by sohan2503001** [comment]
@ronitblenz can u explain me what i have to do here exactly

**Comment by JaynouOliver** [comment]
On a broad basis, see all the divs and words here are center aligned.
Please contact us on discord before making a PR and we shall discuss any further changes with you. @sohan2503001

**Comment by JaynouOliver** [comment]
On a broad basis, see all the divs and words here are c aligned.
Please contact us on discord before making a PR and we shall discuss any further changes with you.

**Comment by sohan2503001** [comment]
yess okk
