### ISSUE TITLE
Optimize the website in the resources page for both the desktop and mobile view

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#136]
![image](https://user-images.githubusercontent.com/88646338/158020270-7e4da811-3d95-40bb-8513-604695f0e978.png)

In the desktop view, there should be 4 elements in a line. 
when switching back to the mobile view, there should be one element in a line.

**Comment by Girlwithasmile** [comment]
I am a contributer at gssoc and would like to work on this

**Comment by ronitblenz** [comment]
@Girlwithasmile Assigned ✨

**Comment by ronitblenz** [comment]
Updates?

**Comment by sohan2503001** [comment]
@ronitblenz if she is unable to solve , i would like to solve issue

**Comment by Girlwithasmile** [comment]
Making pr soon

**Comment by ronitblenz** [comment]
Sure

**Comment by ronitblenz** [comment]
Updates? @Girlwithasmile

**Comment by sohan2503001** [comment]
@ronitblenz is it okk or do you want any changes

**Comment by ronitblenz** [comment]
<img width="252" alt="Screenshot 2022-03-22 at 7 51 03 PM" src="https://user-images.githubusercontent.com/91361382/159503491-51caaf0c-7836-41a6-baab-9348e8a7dbce.png">
The logo circle seems to be distorted
Fix that and make sure its responsive

**Comment by sohan2503001** [comment]
okk

**Comment by sohan2503001** [comment]
![Resources (2)](https://user-images.githubusercontent.com/69068073/159616695-26b9ecdb-e4c8-464d-bc75-bef6974385ba.png)

**Comment by sohan2503001** [comment]
@ronitblenz Is it okk now

**Comment by ronitblenz** [comment]
Make a PR, I need to check it in the deployment
