### ISSUE TITLE
Optimize upcoming event page for the mobile version. 

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#137]
![image](https://user-images.githubusercontent.com/88646338/158020837-da00982e-e1da-48b4-9f58-3d167712406a.png)

in the mobile version, there should be one div per row on the website.

**Comment by ishika1501** [comment]
@JaynouOliver  Sir i would like to work on this issue please assign it to me. Thankyou.

**Comment by Apexshya** [comment]
I am GSSoC'22 contributor and I want to work on this issue. Please assign it to me.

**Comment by ronitblenz** [comment]
@ishika1501 Assigned ✨

**Comment by ronitblenz** [comment]
Updates?
@ishika1501
