### ISSUE TITLE
Implement back-to-top button on all pages of the website

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#139]
Back to top button is missing in some website pages, make sure you implement them on all pages!

**Comment by Girlwithasmile** [comment]
I am a contributer at gssoc and would like to work on this

**Comment by Apexshya** [comment]
I am a contributor at GSSOC'22 and I want to work on this issue. Please assign it to me.

**Comment by ronitblenz** [comment]
@Girlwithasmile You have been assigned to 2 issues, thats why it would be given to @Apexshya 

@Apexshya You are Assigned ✨

**Comment by ronitblenz** [comment]
@Apexshya any updates?

**Comment by sohan2503001** [comment]
@ronitblenz i would like to work on this issue

**Comment by ronitblenz** [comment]
@sohan2503001 Assigned ✨

**Comment by sohan2503001** [comment]
Back to top button was missing on about and contact page.
Can i make a PR.

![Screenshot (302)](https://user-images.githubusercontent.com/69068073/159157769-b972d7cd-2938-4714-a268-b9c2d09d267f.png)
![Screenshot (303)](https://user-images.githubusercontent.com/69068073/159157773-f7635409-2553-450c-883e-957be1748d15.png)

**Comment by ronitblenz** [comment]
Sure @sohan2503001
