### ISSUE TITLE
make the display card count live on page load

### ISSUE THREAD

**Issue by Phalak-Sharma** [Tech-Squad-Community/techsquad-community-website#14]
### Description

make the display card count live on page load 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
You can start working on the issue

**Comment by ronitblenz** [comment]
you are assigned, start working on the issue and create a PR... Good luck

**Comment by flow6979** [comment]
i would like to solve this issue. thank you
