### ISSUE TITLE
Back to top button is getting footer section line over it

### ISSUE THREAD

**Issue by shivam123-dev** [Tech-Squad-Community/techsquad-community-website#144]
**Describe the bug**
Back To Top Button is getting footer's section line on it.

**To Reproduce**
1. Open the **dev** branch using live server on a local machine. 
2. Scroll down to footer section
3. At the beginning of the footer section line, see error

**Expected behavior**

**Screenshots**
![error](https://user-images.githubusercontent.com/81038095/158104581-4b6babcf-154d-480b-8fbe-0027f8641220.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [99.0.1150.39 (Official build) (64-bit)]

**Additional context**
Being a GSSOC'22 contributor, I would like to work on this bug

**Comment by ronitblenz** [comment]
✨ @shivam123-dev  Assigned
