### ISSUE TITLE
Show password functionality in login.html page

### ISSUE THREAD

**Issue by mrudulkolambe** [Tech-Squad-Community/techsquad-community-website#146]
**Describe the bug**
Show password functionality in login.html page

**Expected behavior**
to toggle the type of password input

**Screenshots**
![image](https://user-images.githubusercontent.com/83169198/158238713-5f06ecaf-61c5-4954-a8f2-a2865b48f3e3.png)

**Comment by JaynouOliver** [comment]
go for it! 
Assigned! 
That is a good idea!

**Comment by mrudulkolambe** [comment]
Okayy!!
