### ISSUE TITLE
BUG :  Empty form submission.

### ISSUE THREAD

**Issue by akki251** [Tech-Squad-Community/techsquad-community-website#148]
**Describe the bug**
On Login from user is able to submit the form without email and password validation.

**To Reproduce**
1. Go to Login page
2. Try to submit the form empty.
3. See error

**Expected behavior**
 User should not be able to submit the form empty, 

**Screenshots**
![image](https://user-images.githubusercontent.com/67007034/158512779-cba57713-a886-4a8c-a6a4-81e26eea2c33.png)

**Comment by JaynouOliver** [comment]
yes, that's a nice idea, you can work on it! Go on!
