### ISSUE TITLE
 Homepage Image in the mobile version should be adjusted

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#151]
![image](https://user-images.githubusercontent.com/88646338/158778734-a54cc916-4516-40bf-8c1a-348399897504.png)
You have to adjust the image so that it fits well in the mobile version.

**Comment by HarshitX1002** [comment]
Hey I would Like to work on this issue.
I will make sure image fits well in mobile version of this website.

**Comment by ronitblenz** [comment]
Sure, Assigned @HarshitX1002 ✨
