### ISSUE TITLE
Adding animation in Features Grid sections similar to cover page

### ISSUE THREAD

**Issue by 19arnab190201** [Tech-Squad-Community/techsquad-community-website#154]
### Description

Adding animation in Features Grid sections (Developer's Best Friend & Community Support to make Connections) similar to cover page 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Merged
