### ISSUE TITLE
Adding animation in "Are you ready to grow faster?" section

### ISSUE THREAD

**Issue by 19arnab190201** [Tech-Squad-Community/techsquad-community-website#155]
### Description

Adding animation in "Are you ready to grow faster?" section

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Updates? @19arnab190201

**Comment by 19arnab190201** [comment]
@ronitblenz  tomorrow morning
