### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#162]
**This is under GSSoC'22**

### Description

I want to add form validation in LogIn, Register and ForgotPassword Page

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Can you mention what you mean by validation?

**Comment by ronitblenz** [comment]
Plz dm me on discord 
ronitblenz#6939

**Comment by Kumar-laxmi** [comment]
Form Validation means that like , for example:
### For Password:
- have the minimum length of eight (8) characters
- have at least one lower case character
- have at least one upper case character
- have at least two digits
- have at least one special character

### Confirm Password:
- It will ensure that Confirm Password is same as Password

### Email Validation:
- The first Part should have:
  - Uppercase (A-Z) and lowercase (a-z) letters
  - Digits (0-9)
  - Characters such as ! # $ % & ‘ * + – / = ? ^ _ ` { | } ~
  - Character . ( period, dot or fullstop) but it should not be the first or last character and should not come one after the other
- The Domain name should have:
  - letters
  - digits
  - hyphens
  - dots

**These all are very important since this would prevent invalid data entry into text fields.**

The above are just samples I would apply this to all fields.

**Comment by ronitblenz** [comment]
@Kumar-laxmi Assigned ✨
