### ISSUE TITLE
Create the Blog Page

### ISSUE THREAD

**Issue by ronitblenz** [Tech-Squad-Community/techsquad-community-website#167]
### Description

Here is the UI Design for the Blog page

https://github.com/Tech-Squad-Community/techsquad-community-website/tree/dev/UI

And also, use your creativity if you want
Happy Coding✨

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
@mohitahlawat2001 Updates??

**Comment by ronitblenz** [comment]
ARE YOU WORKING ON IT?

**Comment by Kumar-laxmi** [comment]
@ronitblenz Bro you can assign the issue to me...

**Comment by Kumar-laxmi** [comment]
![image](https://user-images.githubusercontent.com/76027425/160524370-2e60d123-b123-4e6b-a72f-54ce98562a9f.png)
 This is gonna be my grid view

**Comment by Kumar-laxmi** [comment]
@ronitblenz Bro I have completed the Blog Page designing

![image](https://user-images.githubusercontent.com/76027425/160750345-cb2e509c-7fce-47de-a321-4b2cc1e8b697.png)

![image](https://user-images.githubusercontent.com/76027425/160750365-5b1bc9a2-0ad9-4d48-b5ed-244b1464dab9.png)

Assign me ASAP so that I do a PR

**Comment by Kumar-laxmi** [comment]
![screencapture-file-C-Users-Parth-Desktop-VS-Studio-Open-Source-techsquad-community-website-Blog-html-2022-03-30-09_49_09](https://user-images.githubusercontent.com/76027425/160750564-814302d2-c1b6-47f3-8434-f5a71c4aad87.png)
 This is the mobile view

**Comment by ronitblenz** [comment]
Make the design a bit modern... like the other pages we already have...the figma was just a prototype of what will be placed where
