### ISSUE TITLE
Update Footers in all page

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#169]
### Description

The footer in other pages needed to be updating and made same as index.html, like below 

![image](https://user-images.githubusercontent.com/76027425/159502176-21d1845e-8a78-4506-81f0-b064f1ccce43.png)

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Assigned @Kumar-laxmi ✨
