### ISSUE TITLE
Error in spelling

### ISSUE THREAD

**Issue by codercool3r** [Tech-Squad-Community/techsquad-community-website#17]
In contact.html, line 214, there is a minute spelling error.
It is given as 'fill free' instead of 'feel free'.

**Comment by codercool3r** [comment]
> In contact.html, line 214, there is a minute spelling error. It is given as 'fill free' instead of 'feel free'.

Can I solve this issue?

**Comment by Khushi-Mattu** [comment]
Can I solve this issue under GSSOC'22?

**Comment by codercool3r** [comment]
> Can I solve this issue under GSSOC'

**Comment by codercool3r** [comment]
> In contact.html, line 214, there is a minute spelling error. It is given as 'fill free' instead of 'feel free'.

**Comment by codercool3r** [comment]
> > In contact.html, line 214, there is a minute spelling error. It is given as 'fill free' instead of 'feel free'.

Can I solve this issue @ronitblenz

**Comment by ronitblenz** [comment]
Ok, you can solve this, Also Check for other typos as well, if you find some, please rectify

**Comment by ronitblenz** [comment]
<img width="1342" alt="Screenshot 2022-03-01 at 10 20 10 AM" src="https://user-images.githubusercontent.com/91361382/156106897-1b245dc3-ed69-4ee7-88c8-b964e87d9192.png">
Also plz replace the garbage value with some relevant text... you are assigned

**Comment by codercool3r** [comment]
> <img alt="Screenshot 2022-03-01 at 10 20 10 AM" width="1342" src="https://user-images.githubusercontent.com/91361382/156106897-1b245dc3-ed69-4ee7-88c8-b964e87d9192.png">
> 
> Also plz replace the garbage value with some relevant text... you are assigned

Okay sure, thank you
