### ISSUE TITLE
Enhancement : Form Input color validator for better User experience

### ISSUE THREAD

**Issue by akki251** [Tech-Squad-Community/techsquad-community-website#170]
### Description

Please refer to the attached screenshot for better understanding

![image](https://user-images.githubusercontent.com/67007034/159545652-1581578a-d325-429b-8dfb-8febc5a917a9.png)

- A border will appear below the input, which will be red until the input is invalid and then turn green once it is validated, providing a better user experience.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Nice... @akki251 Assigned✨

**Comment by ronitblenz** [comment]
@akki251 Updates?

**Comment by akki251** [comment]
Yes, just about to create the PR
