### ISSUE TITLE
Show/Hide Password

### ISSUE THREAD

**Issue by ayush25102001** [Tech-Squad-Community/techsquad-community-website#175]
### Description

Can I add the show and hide password button in the signUp form as present in the login form?
participant under gssoc’22.

### Domain

Frontend Dev React/Angular/Vue

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Sure @ayush25102001 You are assigned✨
