### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by pranavsuriya-sr** [Tech-Squad-Community/techsquad-community-website#18]
### Description

Adding a scroll to top button at the bottom right of the page will help the users for easy navigation to the top.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by pranavsuriya-sr** [comment]
I would like to work on this issue under gssoc'22 @ronitblenz

**Comment by Khushi-Mattu** [comment]
I would like to work on this issue under gssoc'22 @ronitblenz

**Comment by harshjohar** [comment]
I would like to work on this issue under gssoc'22 @ronitblenz

**Comment by nitishsaini706** [comment]
hi @ronitblenz i would like to try my hands on this task , I'm a complete beginner ,so would like to contribute under GSSOC 2022

**Comment by ronitblenz** [comment]
@pranavsuriya-sr You can work on this issue
Good Luck

**Comment by abh139** [comment]
I want to work on this
