### ISSUE TITLE
Contact page cards alignment

### ISSUE THREAD

**Issue by Pranai2518** [Tech-Squad-Community/techsquad-community-website#180]
### Description

The cards which are there on the contact page were not in the same alignment.

![contact](https://user-images.githubusercontent.com/75829770/160275040-9559a7a9-48ab-4358-a90e-5406663bac11.png)

I would like to work on this issue as a Gssoc participant. please assign me.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Sure go ahead
