### ISSUE TITLE
Resource Page Improvement 

### ISSUE THREAD

**Issue by Ritika122001** [Tech-Squad-Community/techsquad-community-website#181]
### Description

Link the resources in the resource page 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
We don't have the pages ready yet... can you create another issue which is to create those pages.... same as of resource cards

**Comment by Ritika122001** [comment]
Alright. Could we make a page of particular resource card with all the links of websites that provide tutorials for that particular resource?

**Comment by ronitblenz** [comment]
Not only tutorials.. 
https://devohub.vercel.app/
Scroll through this website, we want to take the resources from here

**Comment by ronitblenz** [comment]
@Ritika122001 Will you create an issue ?

**Comment by Ritika122001** [comment]
Next week, I have my internal exams . Therefore, I cannot work until then.

**Comment by ronitblenz** [comment]
Ok ...make an issue next week
