### ISSUE TITLE
Bug in Resource page of Mobile version

### ISSUE THREAD

**Issue by sohan2503001** [Tech-Squad-Community/techsquad-community-website#187]
**Describe the bug**
Footer section of Resource page in Mobile version is not properly aligned.

**Screenshots**
![Screenshot (316)](https://user-images.githubusercontent.com/69068073/161313116-3c74b8b4-79f9-4996-861d-cb610d2dc3a3.png)

**Comment by ronitblenz** [comment]
Assigned @sohan2503001
