### ISSUE TITLE
Resolving card in Mobile View

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#188]
**THIS IS UNDER GSSoC'22**

### Description

We can see that the cards aren't well organized in Mobile View: 

![image](https://user-images.githubusercontent.com/76027425/161362389-a0f91c78-ccc7-4fcd-b28a-2b4eff77d6b1.png)

### Solution
The cards should be aligned in such a way that, one card appears per row

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by Aslam-13** [comment]
Hi, 
pls assign this to me.

**Comment by ronitblenz** [comment]
@Kumar-laxmi Assigned ✨
