### ISSUE TITLE
Labels should be on top of input boxes in login and registration form

### ISSUE THREAD

**Issue by Adhetya** [Tech-Squad-Community/techsquad-community-website#189]
**Describe the bug**
The labels for the login and registration form should come before giving input. However, here the label comes after input

**To Reproduce**
1. Go to login/registration page

**Expected behavior**
Form label should come before the input box

**Screenshots**
<img width="1440" alt="Screenshot 2022-04-02 at 9 53 24 PM" src="https://user-images.githubusercontent.com/20537150/161392150-46dd69f7-10ed-488c-87d9-55eb3d6a5476.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Adhetya** [comment]
I am a GSSOC 22 contributor. Please assign this issue to me.

**Comment by JaynouOliver** [comment]
Okay, go for it. @Adhetya
