### ISSUE TITLE
Add a Registration page

### ISSUE THREAD

**Issue by Chandana-23** [Tech-Squad-Community/techsquad-community-website#19]
### Description

want to add a registration page to the website.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Always create an issue and ask admin or mentor if its really needed or not... It could have happened that you already made a PR but it was not really needed after all, any ways... you were lucky

Good job... Happy Contributing
