### ISSUE TITLE
Fix the dropdown button

### ISSUE THREAD

**Issue by Shreyaar12** [Tech-Squad-Community/techsquad-community-website#192]
**Describe the bug**
Fixing the dropdown button in the navigation bar in the blog page

**To Reproduce**
1. Go to 'blogs'
2. Click on 'drop down menu'
3. See error

**Expected behavior**
The drop down bar does not work in the blog page

**Screenshots**
![Screenshot (1399)](https://user-images.githubusercontent.com/91542376/161397185-f59b54d3-71c4-407f-8b16-f61ac16c2103.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [100]

**Comment by Shreyaar12** [comment]
Please assign this issue to me

**Comment by JaynouOliver** [comment]
Okay go for it. @Shreyaar12
