### ISSUE TITLE
Bug in login page of mobile 

### ISSUE THREAD

**Issue by codingkush** [Tech-Squad-Community/techsquad-community-website#194]
**Describe the bug**
Register button of login page in Mobile version is not properly visible.

**Screenshots**

![Screenshot_20220403-144037~3](https://user-images.githubusercontent.com/78756312/161420665-366ac164-0a2f-4c79-980c-1ac433172f87.png)

**Comment by codingkush** [comment]
I'm a GSsoc 22 contributer and i  want to work on this issue.pls assign me under GSsoc 22

**Comment by ronitblenz** [comment]
Also. there are some other elements hidden behind the footer
Fix that

**Comment by codingkush** [comment]
Ok 😊
