### ISSUE TITLE
Adding a link to Blog Page in Footer

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#195]
### Description

In footer across all pages we can include a link to Blog Page since now we have a Blog Page.

![image](https://user-images.githubusercontent.com/76027425/161426063-320f10a4-b9b8-484d-9c41-ffd32bd79b32.png)

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by JaynouOliver** [comment]
okay go for it
