### ISSUE TITLE
Cards not of equal size for images in about page

### ISSUE THREAD

**Issue by Adhetya** [Tech-Squad-Community/techsquad-community-website#196]
**Describe the bug**
Image cards are not of equal size in desktop view

**To Reproduce**
1. Go to footer
2. Click on Community

**Expected behavior**
Image cards should be of equal size for consistency

**Screenshots**
<img width="1440" alt="Screenshot 2022-04-04 at 6 59 22 AM" src="https://user-images.githubusercontent.com/20537150/161459713-ea4cf776-b0c4-4d22-b0c2-4552b4297f77.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JaynouOliver** [comment]
We can resize the image and the cards will be resized. We have intentionally not done it.
