### ISSUE TITLE
Create individual Blog Pages

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#198]
### Description

In my last PRs I created a Blog Page that contains all Blogs in one page, but we can further enhance it by creating a Single Blog Page that is opened up when we click ```Read More```.

These Pages would host individual Blogs that has been selected by users & like a typical blog page it would also have a Comment section.

Please refer below images for the idea that I am suggesting

![image](https://user-images.githubusercontent.com/76027425/161675331-3533b212-697a-4b3d-82cc-94787615ef52.png)
![image](https://user-images.githubusercontent.com/76027425/161675354-35058bbc-2b32-43f4-86cf-e698f7899b51.png)

And in Comment section
![image](https://user-images.githubusercontent.com/76027425/161675400-a2c9f07b-d8a0-410a-b286-2c5175a62e9f.png)

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by JaynouOliver** [comment]
it will be nice to see that type of implementation on the website, go for it.
