### ISSUE TITLE
UI Design for the Resources Page (Figma)

### ISSUE THREAD

**Issue by ronitblenz** [Tech-Squad-Community/techsquad-community-website#2]
Design a minimal Resource page on Figma according to the color code and theme of our homepage
Try to make it as minimal as possible and easy to use with a great User Experience.

For reference
<img width="1336" alt="Screenshot 2022-02-22 at 1 32 34 AM" src="https://user-images.githubusercontent.com/91361382/155019657-c44fd19f-d2f0-49f9-a5bf-d5656307b8db.png">
<img width="1417" alt="Screenshot 2022-02-22 at 1 33 14 AM" src="https://user-images.githubusercontent.com/91361382/155019666-1b12841b-8765-47d9-999c-b36b72e46307.png">

**Comment by ishika1501** [comment]
@ronitblenz  i am quite good with Ui/Ux , please assign it to me.

**Comment by ronitblenz** [comment]
You will be assigned on 1st March

**Comment by ronitblenz** [comment]
You can start working on the issue from now on, I will assign you on 1st merge, then you can create a PR 
Because you have much time left

**Comment by ishika1501** [comment]
@ronitblenz  thankyou sir

**Comment by ishika1501** [comment]
@ronitblenz  should I add the link to the figma or the images of the pages , also do i need to create a new folder sir ?

**Comment by ronitblenz** [comment]
Send me the link first
Let me check

**Comment by ronitblenz** [comment]
you are assigned, start working on the issue and create a PR... Good luck

**Comment by ronitblenz** [comment]
> @ronitblenz should I add the link to the figma or the images of the pages , also do i need to create a new folder sir ?

Plz send me the link, if I approve the design then only make a PR
