### ISSUE TITLE
Add server, create backend for user signin and signup

### ISSUE THREAD

**Issue by AdnanMuzavor** [Tech-Squad-Community/techsquad-community-website#200]
### Description

Add user signup and login functionality
->Schema for user
->API for signup and login
->JWT token for authorization

### Domain

MERN

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by JaynouOliver** [comment]
we will be doing that in the react version of the website, please check out the react branch when it's ready
