### ISSUE TITLE
Improve the UI of Login Page 

### ISSUE THREAD

**Issue by 19arnab190201** [Tech-Squad-Community/techsquad-community-website#201]
### Description

The UI of the login page is too simple can be given some creative  touch .

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by JaynouOliver** [comment]
Let's see what you can do! go for it!
