### ISSUE TITLE
Login/signUp Buttons in Header

### ISSUE THREAD

**Issue by ayush25102001** [Tech-Squad-Community/techsquad-community-website#202]
### Description

Login and SignUp options are in the footer can I create the respective buttons in the header such that render the login and signUp forms. Its more user friendly if these options are present at the top. 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by JaynouOliver** [comment]
okay go for it
