### ISSUE TITLE
Fix footer links on every page

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#204]
Footer links are not the same on every page, fix it

![image](https://user-images.githubusercontent.com/88646338/162601370-b18a886d-2af7-407d-9dc2-69863267a04b.png)

![image](https://user-images.githubusercontent.com/88646338/162601502-7f444e9a-115a-4818-b83e-3caa3a2aaa83.png)

**Comment by Adhetya** [comment]
Can I work on it? And which footer links do you need? The links in first image or second one?

**Comment by JaynouOliver** [comment]
Go for it, 
the links of the first image @Adhetya

**Comment by Adhetya** [comment]
@JaynouOliver, as far as I can see, the footer links are same in all pages of the website. I can see different footer links in https://techsquadcommunity.tech/registration.html but I thought the codebase was based on the preview in github pages.

**Comment by sohan2503001** [comment]
Can u assign me this issue , if he couldn't do it
