### ISSUE TITLE
Buttons not linked

### ISSUE THREAD

**Issue by Aniket1026** [Tech-Squad-Community/techsquad-community-website#230]
![Screenshot (72)](https://user-images.githubusercontent.com/92184189/163855713-00ed4127-e1cd-4eba-aeac-3329d76b8257.png)

Both the buttons are not linked with the respective destination .
So would like to link the buttons with discord and mailing list respectively.

**Comment by JaynouOliver** [comment]
this is intentionally done

**Comment by Aniket1026** [comment]
ohhh ok sir
