### ISSUE TITLE
Linking 6 cards to there own individual page

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#232]
### Description

In ```index.html``` we have following six cards:
![image](https://user-images.githubusercontent.com/76027425/163935815-0d3c2ed7-e999-47d6-8f90-ccce4ead3906.png)

These 6 cards lead to outside links, but we could create 6 more individual Blog Pages like page and link it to it. 
This could be safe, as in future if those online blogs are removed then it would pop-up ```ERROR Page not found```

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by Kumar-laxmi** [comment]
@ronitblenz @JaynouOliver Please review this PR

**Comment by JaynouOliver** [comment]
Closing all issues, work u may work on the react version.
