### ISSUE TITLE
Navbar in contact page 

### ISSUE THREAD

**Issue by kanishak11-cyber** [Tech-Squad-Community/techsquad-community-website#235]
![image](https://user-images.githubusercontent.com/84625838/164954588-9291e23e-aad1-4342-bf1b-facd9de7c948.png)

NavBar in contact.html is very large need to be small.
Browser: brave, google,etc

**Comment by kanishak11-cyber** [comment]
@admin I want to work on this issue

**Comment by JaynouOliver** [comment]
All issues here are henceforth closed. HAve a look at the issues for the react version.
