### ISSUE TITLE
Create a transparent Navbar using Next js 

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#239]
### Description

![image](https://user-images.githubusercontent.com/88646338/167485613-cf6f95de-30c4-4150-8307-8dade3877aa0.png)

Refer to https://www.helium.com/ to have a look at the navbar. 
Use tailwind CSS. 
import all modules required and remove unnecessary files and codes. 

navbar should contain all the text in the navbar of https://techsquadcommunity.tech/

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by Sukriti-m** [comment]
I am a GSSoC'22 contributor. Please assign this issue to me.

**Comment by JaynouOliver** [comment]
Go for it!

**Comment by JaynouOliver** [comment]
@Sukriti-m any update?

**Comment by Sukriti-m** [comment]
> @Sukriti-m any update?
![Screenshot (69)](https://user-images.githubusercontent.com/93239528/168244001-34e05e84-5d22-4775-942e-eb009f14573d.png)

I am unable to run the development server. Could you please tell me what am I doing wrong here?

**Comment by JaynouOliver** [comment]
@Sukriti-m, as of now it is not necessary to keep the file structure intact. you can create a new next JS app and then make the necessary changes, create a page with the following navbar to make PR.

**Comment by Sukriti-m** [comment]
> @Sukriti-m, as of now it is not necessary to keep the file structure intact. you can create a new next JS app and then make the necessary changes, create a page with the following navbar to make PR.

Alright, thank you. I will make a PR very soon.

**Comment by JaynouOliver** [comment]
Sure! Keep it up!

**Comment by JaynouOliver** [comment]
@Sukriti-m if you fail to make a PR within the next 12 hours, I will have to unassign you, according to the normal standard, 4-5 days can be assigned for a hard level issue.

**Comment by sohan2503001** [comment]
Can you assign me this issue

**Comment by JaynouOliver** [comment]
Yes go for it! @sohan2503001

**Comment by sohan2503001** [comment]
@JaynouOliver Is it okk or should i do any changes , to show transparency i have just use random image
![Navigation-Bar](https://user-images.githubusercontent.com/69068073/170620641-07e03138-67ef-4924-ad2d-6acbc799b495.png)

**Comment by JaynouOliver** [comment]
don't highlight upcoming events in blue, make the whole navbar black and fonts white. see the above image. it should be similar to that.

**Comment by sohan2503001** [comment]
Is it okk now.
![Navigation-Bar (1)](https://user-images.githubusercontent.com/69068073/170767153-58878c45-b6d8-4614-9b14-f3009cc833af.png)

**Comment by JaynouOliver** [comment]
yes, that's okay! make a pr !
