### ISSUE TITLE
Create a new section for "handpicked technologies" using Next js

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#241]
### Description

![image](https://user-images.githubusercontent.com/88646338/167487931-3fc45c61-7827-4d84-bfa0-04d25386fa59.png)

use this image for reference. visit helium.com for reference. 

![image](https://user-images.githubusercontent.com/88646338/167488018-8871a8f7-7bc0-4077-8028-5f0f1134a248.png)

the output should be like the above image. Use the CSS (use tailwind CSS) and fonts in the above first image to build the latter. 

apply the animation effects used in the 2nd image. To view the animation effects visit https://techsquadcommunity.tech/

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by vasantisuthar** [comment]
I am a GSSOC'22 contributor and I would like to work on this issue.
Please assign this to me

**Comment by JaynouOliver** [comment]
Go for it! @vasantisuthar

**Comment by JaynouOliver** [comment]
@vasantisuthar updates? Try to provide a PR by the next 12 hours, see if you can. If not, unfortunately the organization have to unassign you.

**Comment by prabhakar-dessai** [comment]
Hey, can you assign this issue to me under GSsoc'22.

**Comment by JaynouOliver** [comment]
Hey, go for it. @prabhakar-dessai

**Comment by JaynouOliver** [comment]
@prabhakar-dessai you have one more day, all issues will be closed!
