### ISSUE TITLE
Create a seperate Blogs page and link it to the navbar "Blogs" button (in Next js) 

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#242]
### Description

This issue will be assigned only after the navbar issue is complete.
![image](https://user-images.githubusercontent.com/88646338/167490462-48b7be8e-1143-492c-893d-a6e133fb3c65.png)

The blog page should have a design like this and the colors should match with the theme of the website. 

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by AdnanMuzavor** [comment]
I am GSSOC contributor and I would like to work on this issue.
However is it ok if I use normal CSS for designing and bootstrap for responsiveness?

**Comment by JaynouOliver** [comment]
Go for it. Connect with me in discord before you start working, need to discuss about how you'll proceed.

**Comment by JaynouOliver** [comment]
updates? @AdnanMuzavor ?

**Comment by AdnanMuzavor** [comment]
Check this link out @JaynouOliver,I have given all updates through this screen recording .
Link: https://www.recordjoy.com/view/oOAxMmjDmr3Zp1y4aEx9
However due to tight schedule of offline college I could not make it to learn and apply tailwind CSS, I hope you'll understand!!.
Rest I have done(directly using next.js).

**Comment by JaynouOliver** [comment]
That was great. I understand your pain about offline college, it's alright, please make a PR.

**Comment by AdnanMuzavor** [comment]
Hehe thanks @JaynouOliver .
Done.
