### ISSUE TITLE
Create a section of page like the image given. (Using Next js) 

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#243]
### Description

![image](https://user-images.githubusercontent.com/88646338/167490072-426290ec-9121-4ef9-857f-e841e7b205a1.png)

Make 6 cards instead of 3 cards and match the background color with the website theme. (https://techsquadcommunity.tech/)

### Domain

Open Source

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by navyasharma0203** [comment]
Can I work on this??

**Comment by JaynouOliver** [comment]
yeah, sure go for it?

**Comment by JaynouOliver** [comment]
updates @navyasharma0203 ?

**Comment by navyasharma0203** [comment]
> updates @navyasharma0203 ?

Yes...I am working on it :)

**Comment by JaynouOliver** [comment]
:)

**Comment by JaynouOliver** [comment]
@navyasharma0203 you have one more day, all issues will be closed.

**Comment by piyusha2001** [comment]
@JaynouOliver  can I work on this ? I will make a PR by tomorrow itself . Its been more than 10 days since it has been assigned.

**Comment by JaynouOliver** [comment]
no more time left. can make a pr directly, will assign the tags @piyusha2001
