### ISSUE TITLE
Create social links functional button at the end of the main page (using Next Js)

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#244]
### Description

![image](https://user-images.githubusercontent.com/88646338/167491074-cda54a4f-019f-4b7c-bd0a-3d16cbe9406e.png)

When you click on the button, all the links shall fade in, in a circular fashion one at a time. visit https://jellysmack.com/creator-program/ website for more reference.

### Domain

Open Source

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by prabhakar-dessai** [comment]
Hey, I'm a GSsoc participant, can i work on this issue?

**Comment by JaynouOliver** [comment]
updates? @prabhakar-dessai

**Comment by raaghavrm** [comment]
Hey
Wanna work on this, please assign this to me.
Thanx mate
Reference: gssoc'22
