### ISSUE TITLE
Re-organising JS functions 

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#26]
### Description

The JavaScript function window.addEventListener() is appearing in multiple HTML files, so that could be organised into a single JS file to increase readability.

### Domain

JavaScript_Domain

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
You are assigned.. good luck

**Comment by Kumar-laxmi** [comment]
Already Pulled request

**Comment by ronitblenz** [comment]
Yeah merged
