### ISSUE TITLE
Adding shadow to cards

### ISSUE THREAD

**Issue by AshutoshDash1999** [Tech-Squad-Community/techsquad-community-website#27]
### Description

Hi, I want to add shadow to the card components. Can you please assign this issue to me?

### Domain

Frontend Dev HTML/CSS/JS

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
You are assigned @AshutoshDash1999 
Good Luck

**Comment by mahi-19** [comment]
I am a GSSOC'22 participant and want to work on this issue.pls assign this issue to me

**Comment by ronitblenz** [comment]
Issue is solved
