### ISSUE TITLE
Aligning of Cards in team page

### ISSUE THREAD

**Issue by aritra1804** [Tech-Squad-Community/techsquad-community-website#28]
Hey I would like to work on formatting of images in the cards of team page  for GSSOC 22. Currently it in not aligned and in a up down fashion.

**Comment by ronitblenz** [comment]
Actually, the photos can adjust when they are cropped in the same sizes... So this issue is not required right now.
I am sorry, but you can work on other issues as well and make some good issues too.

**Comment by JaynouOliver** [comment]
@aritra1804 that issue is already sorted, if we resize the image, we can solve that, it's just that we are out of good photographs you know! And please ping the mentor from next time you create an issue!

**Comment by aritra1804** [comment]
Sure
