### ISSUE TITLE
Make Upcoming Event Page 

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#3]
Make a minimal Upcoming Event page according to the colour code and theme of our homepage
Try to make it as minimal as possible and easy to use with a great User Experience.

For reference
<img width="1440" alt="Screenshot 2022-02-25 at 12 26 35 AM" src="https://user-images.githubusercontent.com/91361382/155589377-80f97c8a-0e60-4ad5-8062-99436131a676.png">

**Comment by Deekshith44** [comment]
I would like to work on this issue

**Comment by ronitblenz** [comment]
> Hi I would like to work on this issue!!!

It's a first come first serve basis system. If the person before you fails to deliver the job within due time, it will be forwarded to you. Till then you can contribute to other issues and raise your own issues as well... If the issue seems to be valid, we will assign you and we can merge your PR

**Comment by ronitblenz** [comment]
you are assigned, start working on the issue and create a PR... Good luck
