### ISSUE TITLE
Improving Cards of the site

### ISSUE THREAD

**Issue by rajprem4214** [Tech-Squad-Community/techsquad-community-website#30]
### Description

I want to improve the existing card designs and add some cool animated effects to it.
On hover it will show the description.
 Please assign this to me. I  m a contributor of GSSoC'22.

### Domain

MERN

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by JaynouOliver** [comment]
This issue already exists @rajprem4214 , and please contact the mentors before creating an issue from the next time.
