### ISSUE TITLE
Adding animations to existing card improving its ui

### ISSUE THREAD

**Issue by rajprem4214** [Tech-Squad-Community/techsquad-community-website#33]
### Description

Adding animations to the existing Cards and its ui enhancement. please assign this issue. i m a contributor at GSSoc'22.

### Domain

MERN

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Plz contact me on discord, after that I would proceed with the assigning part

**Comment by ronitblenz** [comment]
This issue is solved already... Thank you
