### ISSUE TITLE
Card components break on all screens

### ISSUE THREAD

**Issue by akki251** [Tech-Squad-Community/techsquad-community-website#34]
### Description

These card components are breaking, the text is not properly aligned with the badge.

![Issue #component Breaking](https://user-images.githubusercontent.com/67007034/156121272-6db78543-8a69-4ced-b938-f0d71a6fc4e3.png)

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by JaynouOliver** [comment]
Go for it @akki251

**Comment by akki251** [comment]
Thanks @JaynouOliver

**Comment by JaynouOliver** [comment]
@akki251 connect with me in our discord channel and make sure you show me the result before you make a PR.
Good Luck

**Comment by akki251** [comment]
sure @JaynouOliver

**Comment by akki251** [comment]
Hi, Here is result, Shall I create the pull request  

![Uploading #card-break-fixed.png…]()

**Comment by JaynouOliver** [comment]
Yes Create a PR
