### ISSUE TITLE
Add an abstract image in the background of the specified division

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#35]
### Description

You are required to add a vector image in the background of this division of the website.
![image](https://user-images.githubusercontent.com/88646338/156118854-ebdc1b04-19ee-4e13-bcfd-e3eae2cce774.png)

Something Like this :
![image](https://user-images.githubusercontent.com/88646338/156124442-262ac32c-f64d-43e9-882d-8fbcb9f589b2.png)
The image is just for reference
Connect with the mentors to show your designs.

### Domain

Open Source

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by StillAbeginnerr** [comment]
i want to work on this issue

**Comment by JaynouOliver** [comment]
Go for it! @StillAbeginnerr

**Comment by HarshKumarChoudary** [comment]
If this issue will not be done, then please consider me eligible for it.
