### ISSUE TITLE
Figma design for the Blogs Page of the website

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#36]
### Description

Description: Make the design in sync with the color and style of the website and connect with the mentors to make the necessary changes.

### Domain

Open Source

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ShashankRaturi** [comment]
Can i design the blogs page?

**Comment by JaynouOliver** [comment]
Yes, go for it. Good Luck!

**Comment by ronitblenz** [comment]
@ShashankRaturi Any Updates?

**Comment by JaynouOliver** [comment]
@ShashankRaturi unassigning you because you have failed to submit a prototype, as said previously, the time limit for the issue is  3 days.

**Comment by JaynouOliver** [comment]
@ShashankRaturi today is the last date, you have to be unassigned if you fail to show us any update.  24 hours left! Let's hope for the best! Good Luck!

**Comment by ShashankRaturi** [comment]
Hello Sir , 
I have made a figma design , please tell me how to get it approved?

**Comment by ronitblenz** [comment]
You can get e shareable link from there ..if you cant find it... Send some screenshots

**Comment by ShashankRaturi** [comment]
Yes
https://www.figma.com/file/LyqiPckKwit2rB366iFWfC/Blogpage_first_prototype?node-id=0%3A1

**Comment by ronitblenz** [comment]
This doesnt look modern ..  and match the colour scheme with our website.... You need to change the design ..make it look modern

**Comment by Daksh-jha** [comment]
@JaynouOliver, I would like to do this task under GSSOC, please assign it to me.

**Comment by ronitblenz** [comment]
@ShashankRaturi Any updates?

**Comment by ShashankRaturi** [comment]
Kindly un-assign me from this issue for now.

**Comment by ronitblenz** [comment]
Ok @ShashankRaturi 

@Daksh-jha you are assigned ✨

**Comment by Daksh-jha** [comment]
https://www.figma.com/proto/fB8l24KguedLI4usjmQwY5/Blog-Page?scaling=contain&page-id=0%3A1&node-id=201%3A2

Can you please review it, so that I can make PR ?

**Comment by ronitblenz** [comment]
Its great... You did a great work planning everything inside the single screen... You just need to make it more modern and attractive... Keeping in mind it should be minimal

**Comment by Daksh-jha** [comment]
Okk I can make it more attractive but I can't get what, you mean by modern like can you tell what feature or idea you are having in your mind  so that I can try to implement it ?

**Comment by ronitblenz** [comment]
Change the colour scheme a bit, its not matching with our website...  
Keep the colours a bit light and sober, you can get the idea from the home page itself

And the format is really great... Its unique, i liked it

**Comment by Daksh-jha** [comment]
https://www.figma.com/proto/fB8l24KguedLI4usjmQwY5/Blog-Page?node-id=201%3A2&scaling=contain&page-id=0%3A1

Sir, I have done some changes and set the colors according to main website. Please check and tell if I can make PR now or not :(

**Comment by ronitblenz** [comment]
Make a PR
Provide a PNG/SVG format in the assets folder > UI , and also give the .figma file there...

**Comment by ronitblenz** [comment]
You should make the PR in our DEV branch (default) 
Your PR is not appearing to us, you committed some mistake
<img width="723" alt="Screenshot 2022-03-12 at 1 03 28 PM" src="https://user-images.githubusercontent.com/91361382/158008664-860c6e0f-f9f5-4ccf-9c6b-6a9ee92ad1b2.png">

You made pr on your forked repo🙃
