### ISSUE TITLE
Add floating animation to this image and add some effect to it as the mouse pointer hovers over the image

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#39]
### Description

Description: 
Add floating animation to this image and add some effect to it as the mouse pointer hovers over the image.
![image](https://user-images.githubusercontent.com/88646338/156130777-7aa7a474-4771-4de4-bf4b-d6279ba2d7cf.png)

refer to this image on https://gssoc.girlscript.tech/ for reference
![image](https://user-images.githubusercontent.com/88646338/156130953-7f7a0f3b-19c8-4808-a327-ed789f619f3b.png)
Note: Images are taken only for reference and are not intended to be copied! 
Contact the mentors on the Discord channel before making a PR! 
Thank You! 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by HarshKumarChoudary** [comment]
I would like to contribute to this. Please assign it to me.

**Comment by JaynouOliver** [comment]
@HarshKumarChoudary go for it!
