### ISSUE TITLE
Add Animation to the cards while cursor hovers

### ISSUE THREAD

**Issue by ronitblenz** [Tech-Squad-Community/techsquad-community-website#4]
<img width="1252" alt="Screenshot 2022-02-22 at 2 25 53 AM" src="https://user-images.githubusercontent.com/91361382/155025277-795ab847-7bc3-4230-b2d8-6ddc78679016.png">

Add some animation to those cards, as if the cards float and drop a shadow
Also add some color change or a ripple effect.

**Comment by ishika1501** [comment]
@ronitblenz sir , i would like to do this project , please assign it to me.

**Comment by ronitblenz** [comment]
You will be assigned on 1st March

**Comment by ronitblenz** [comment]
You can start working on the issue from now on, I will assign you on 1st march, then you can create a PR 
Because you have much time left

**Comment by ronitblenz** [comment]
you are assigned, start working on the issue and create a PR... Good luck

**Comment by flow6979** [comment]
@ronitblenz I would like to contribute to this section of the project. thank you
