### ISSUE TITLE
Add toggle animation to the sidebar

### ISSUE THREAD

**Issue by aadityasinha-dotcom** [Tech-Squad-Community/techsquad-community-website#40]
### Description

Add toggle animation to the sidebar.

![image](https://user-images.githubusercontent.com/75474786/156142397-50c6c9f0-db96-4830-a64d-71bdef098c77.png)

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Can you show me a sample of what you want to do?

**Comment by aadityasinha-dotcom** [comment]
> Can you show me a sample of what you want to do?

Something like this.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/75474786/156149507-091db836-c441-464d-a31c-cf37cd10af04.gif)

**Comment by JaynouOliver** [comment]
Alright, go for it! @aadityasinha-dotcom 
Join the discord server and make sure you show us before you make a PR

**Comment by HarshKumarChoudary** [comment]
If this Issue is not solved, then please consider me eligible for it.

**Comment by ronitblenz** [comment]
Any update @aadityasinha-dotcom ?
Level1 issues are given 24 hrs. I hope you will make a PR by today, else it will be forwarded to the next contributor in the queue.

**Comment by aadityasinha-dotcom** [comment]
> Any update @aadityasinha-dotcom ?
> Level1 issues are given 24 hrs. I hope you will make a PR by today, else it will be forwarded to the next contributor in the queue.

Sorry didn't know about 24hr stuff. Will make PR today.

**Comment by ronitblenz** [comment]
> > Any update @aadityasinha-dotcom ?
> > Level1 issues are given 24 hrs. I hope you will make a PR by today, else it will be forwarded to the next contributor in the queue.
> 
> Sorry didn't know about 24hr stuff. Will make PR today.

Its alright.... Make a PR today itself then...
