### ISSUE TITLE
Optimization of CSS Class and JS Function Declaration

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#41]
### Description

In **_register.html_** the CSS Classes and JS Function call can be optimized to reduce the lines of code

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by Kumar-laxmi** [comment]
register.html requires code optimization

**Comment by ronitblenz** [comment]
@Kumar-laxmi Go Ahead

**Comment by Kumar-laxmi** [comment]
Hey I have sent pull request
