### ISSUE TITLE
Turn the cards into Clickable links

### ISSUE THREAD

**Issue by ronitblenz** [Tech-Squad-Community/techsquad-community-website#5]
<img width="1170" alt="Screenshot 2022-02-22 at 2 48 59 AM" src="https://user-images.githubusercontent.com/91361382/155027489-f8f1bbd4-ce00-415d-9048-848bfee86990.png">

Make sure that the cards turn into a clickable link that redirects to a relevant resource where the topic is explained from a broader perspective.

**Comment by AshutoshDash1999** [comment]
Hey, I want to work on this issue. Can you please assign this one to me?

**Comment by ronitblenz** [comment]
The issues will be assigned 1st march onwards according to gssoc guidelines.

**Comment by ronitblenz** [comment]
You can start working on the issue from now on, I will assign you on 1st march, then you can create a PR 
Because you have much time left

**Comment by ronitblenz** [comment]
you are assigned, start working on the issue and create a PR... Good luck
