### ISSUE TITLE
 add Carousel slideshow for upcoming event

### ISSUE THREAD

**Issue by Rishabh-Gaud** [Tech-Squad-Community/techsquad-community-website#52]
### Description

 Carousel sliders can help organize serial content while boosting engagement. and I want to help.

### Domain

Frontend Dev HTML/CSS/JS

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by Rishabh-Gaud** [comment]
I am Rishabh Gaud GSSOC'22 participant. I want to work upon this issue

**Comment by ronitblenz** [comment]
This is not required for now, 
Thanks for showing interest
Please make sure you connect with the admin or mentors of this project before making any issue
So that you know if its required or not and also it doesn't spam the issues Section.

Checkout other issues if you feel like
