### ISSUE TITLE
Enhanced the display

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#55]
### Description

Description: This is not a GSSOC issue.

### Domain

Open Source

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by Anushka-2003** [comment]
Please assign this issue to me.

**Comment by JaynouOliver** [comment]
go for it !
