### ISSUE TITLE
Modify the footer links

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#6]
![image](https://user-images.githubusercontent.com/88646338/155031007-f400c1d3-9542-4348-8c34-c5fd33a6770f.png)
Connect with the mentor/admin of this project to get started with this issue.

**Comment by HarshKumarChoudary** [comment]
Could you please assign this task to me. I could contribute to this.

**Comment by ronitblenz** [comment]
Hi, You can start working on the issue from now on, I will assign you on 1st march, then you can create a PR
Because you have much time left

And plz connect with me or @JaynouOliver over discord to learn more about the issue

**Comment by uhini0201** [comment]
Hi, I would like to work on that

**Comment by JaynouOliver** [comment]
@uhini0201 You can look into some other issues. The assigning of issues happens on a first come first serve basis.

**Comment by JaynouOliver** [comment]
@HarshKumarChoudary you are assigned, start working on the issue and create a PR... Good luck

**Comment by HarshKumarChoudary** [comment]
@JaynouOliver  where could we find the mentors for getting started

**Comment by ronitblenz** [comment]
@HarshKumarChoudary Whats the update regarding this issue? You dont have time left.
I insist you to complete this issue by today and make a PR

**Comment by StillAbeginnerr** [comment]
If this issue is not assigned to somebody or passed the deadline as there is no mention of issue merge here, could you assign me?

**Comment by HarshKumarChoudary** [comment]
@StillAbeginnerr I am working on it, and will soon make a PR.

**Comment by StillAbeginnerr** [comment]
@HarshKumarChoudary ok bhai

**Comment by HarshKumarChoudary** [comment]
I created the PR #143  Please review it. Thanks.
