### ISSUE TITLE
docs: Add PR Template

### ISSUE THREAD

**Issue by Pradumnasaraf** [Tech-Squad-Community/techsquad-community-website#62]
### Chnages 
- Adding a PR template
- Template path **`.github/PULL_REQUEST_TEMPLATE.md`**

### Template Preview (while creating a PR.)
![Screenshot from 2022-03-01 17-54-32](https://user-images.githubusercontent.com/51878265/156168840-66822d65-3e60-4026-8064-f967d66cf94b.png)

####  Due to that we are also missing out on some checks on the community standards checklist

![Screenshot from 2022-03-01 23-55-37](https://user-images.githubusercontent.com/51878265/156227102-92e53e64-723f-4165-bb92-0de7f60b9837.png)

**Comment by ronitblenz** [comment]
Also add the issue no. section
Assigned
