### ISSUE TITLE
Creating Blog Page

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#64]
### Description

I can see that there is no blog page when clicking blog button.

So I can create one and link it.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
We are waiting for the Figma UI designs for the Blog page. After we get it.... you can work on this, to make a similar stuff

**Comment by Pranai2518** [comment]
I would like to work on this issue.
