### ISSUE TITLE
Create nuemorphic design login page

### ISSUE THREAD

**Issue by muizan** [Tech-Squad-Community/techsquad-community-website#65]
### Description

I would like to create a login page with nuemorphic design as it would sync with the resources where  you have used shadow and stuff and it looks quite beautiful . 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by JaynouOliver** [comment]
send us some samples by connecting with us on discord.

**Comment by muizan** [comment]
![Web capture_2-3-2022_121130_i ytimg com](https://user-images.githubusercontent.com/93467099/156388151-a0384e8c-e67d-4894-8cb3-225bd2d5538e.jpeg)

**Comment by muizan** [comment]
it will look something like this image but more beautiful .

**Comment by ronitblenz** [comment]
Sure go ahead...

**Comment by muizan** [comment]
![Web capture_2-3-2022_204631_127 0 0 1](https://user-images.githubusercontent.com/93467099/156390746-61cc90a0-0e19-4042-9cda-b2ff9fda3c9e.jpeg)

**Comment by ronitblenz** [comment]
Exactly... and plz contact me on discord I have some more info to provide 
ronitblenz#6939

**Comment by muizan** [comment]
> Sure go ahead...

Thankyou for giving me this opportunity .
