### ISSUE TITLE
Design of contact us section

### ISSUE THREAD

**Issue by Priyanshi662** [Tech-Squad-Community/techsquad-community-website#66]
### Description

Description: map can be shifted to be at the same place with contact us . And also phone number field is accepting non numeric characters too. I'm attaching a photo of what I think this section should be like. Kindly see to it
![Screenshot (80)](https://user-images.githubusercontent.com/77521822/156312227-b29030fb-9307-48de-9c1d-b229e38542b3.png)
[](url)

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by JaynouOliver** [comment]
Hi, we are happy with the suggestions that you provided us, but as of now, we feel our website looks well and clear as it is! 
So, we don't need the changes to be done. 
Thank You!
