### ISSUE TITLE
Make 3D vector design to replace the first given image.

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#7]
![image](https://user-images.githubusercontent.com/88646338/155538279-95e98a04-014d-4c01-8a2c-d1fc07770fd8.png)
You are required to make a 3D vector design for the landing page of the website. Connect with the mentors for further guidance. 
Format should be in SVG.
Happy Hacking!

**Comment by StillAbeginnerr** [comment]
I want to work on this issue.

**Comment by JaynouOliver** [comment]
Well, go for it! I will assign you on the first of March as per the rules. Please connect with me on discord (Subhro#8287)and show me the designs so that I can guide you!

**Comment by ronitblenz** [comment]
you are assigned, start working on the issue and create a PR... Good luck
