### ISSUE TITLE
Enhancement : I will transform the about section to a better UI

### ISSUE THREAD

**Issue by akki251** [Tech-Squad-Community/techsquad-community-website#75]
### Description

This looks a bit weird, I will customize with icons and try to make it more better looking !

![contributors issue ](https://user-images.githubusercontent.com/67007034/156342212-80a213a2-10af-4d0d-a66b-d6f4c63ee9ba.png)

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by r3yc0n1c** [comment]
Oops! Someone has already started working on this... Thanks for your interest. Meanwhile, you can look upon other issues or create one after discussing the new issue with the mentor(s) / admin.
