### ISSUE TITLE
Back To Top Button

### ISSUE THREAD

**Issue by r3yc0n1c** [Tech-Squad-Community/techsquad-community-website#76]
**Describe the bug**
The Back to top Button gets wrapped under the Cards when we scroll down in the mobile view.

**To Reproduce**
1. Go to Mobile View
2. Scroll down to the "Learn More" section
3. See the Back-To-Top Button hidden behind the cards

**Expected behavior**
The Back-To-Top Button should float over every element and must be clickable

**Screenshots**
![Screenshot 2022-03-02 173349](https://user-images.githubusercontent.com/57730879/156361115-f3633e47-8a8e-4774-81bc-fa8a7f8a2e98.png)

**Comment by akki251** [comment]
Hi @r3yc0n1c  ,Please assign it to me, I will work on it

**Comment by r3yc0n1c** [comment]
> Hi @r3yc0n1c ,Please assign it to me, I will work on it

go ahead! ✨
