### ISSUE TITLE
Make two 3D vector Image for mentioned portion of the website

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#8]
![image](https://user-images.githubusercontent.com/88646338/155542840-518f0537-5385-4558-8478-bb2ff510e0de.png)

You are required to make two 3D vector designs for the landing page of the website. Connect with the mentors for further guidance.
Formats should be in SVG.
Happy Hacking!

**Comment by abh139** [comment]
I can work on that.
Please assign this to me

**Comment by aritra1804** [comment]
Hey I would like to work this issue in GSSOC 22

**Comment by ronitblenz** [comment]
@abh139 You are assigned.
Please go ahead

**Comment by abh139** [comment]
Thanks

**Comment by JaynouOliver** [comment]
@abh139 Ping me on Discord and show us the designs when you feel you are ready.

**Comment by abh139** [comment]
Yeah sure @JaynouOliver

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue under GSSOC 22. Please assign to me, if @aritra1804 is not going to work.

**Comment by aritra1804** [comment]
I would like to work on it @JaynouOliver

**Comment by ronitblenz** [comment]
> I would like to work on this issue under GSSOC 22. Please assign to me, if @aritra1804 is not going to work.
> 

I am assigning you @HarshKumarChoudary 
Good luck🤞

**Comment by HarshKumarChoudary** [comment]
Could you please provide me with some resources to learn from, so that I could create the images.

**Comment by ronitblenz** [comment]
https://youtu.be/3GzumUieDPY
This is a 5 min tutorial

https://youtu.be/Ib8UBwu3yGA
This is a long tutorial

You can watch them for help

**Comment by ronitblenz** [comment]
Hey, @HarshKumarChoudary 
The vector is updated already by someone... you learn the skill for now.. you can contribute to other issues.
Is it ok?

So.. I am closing this issue... there will be more issues coming dont worry

**Comment by HarshKumarChoudary** [comment]
Ok. Thanks
