### ISSUE TITLE
Shadow effect under the main vector when cursor hovers

### ISSUE THREAD

**Issue by ronitblenz** [Tech-Squad-Community/techsquad-community-website#80]
### Description

<img width="1277" alt="Screenshot 2022-03-02 at 8 47 44 PM" src="https://user-images.githubusercontent.com/91361382/156390640-95ef85ab-3fbf-432c-bd96-3d44abc30872.png">

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by neharaut00** [comment]
I want to work on this issue under GSSOC22.

**Comment by HarshKumarChoudary** [comment]
Please give some example of the effects you want.

**Comment by ronitblenz** [comment]
![Mar-03-2022 08-59-04](https://user-images.githubusercontent.com/91361382/156490675-a69bb41a-825d-4ef6-8d40-f04cd4ff059e.gif)

**Comment by HarshKumarChoudary** [comment]
I had created a PR which fixes this issue. Please review it, Thanks.

**Comment by HarshKumarChoudary** [comment]
Since PR is merged then please close this issue. Thanks.
