### ISSUE TITLE
Adding Animations to the Home Page

### ISSUE THREAD

**Issue by 19arnab190201** [Tech-Squad-Community/techsquad-community-website#82]
### Description

Description:  " Are you ready to grow faster? "  section UI improvement by strictly following the design patterns of the project

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
Can you explain to me your approach to this issue?

**Comment by VIDHI-BAJAJ** [comment]
Can you assign me the issue i know how to solve it

**Comment by 19arnab190201** [comment]
> Can you explain to me your approach to this issue?

@ronitblenz  the contents of the cards of this section can be aligned more beautifully hence making the ui better 

below is the img of existing design
![TechSquad Community](https://user-images.githubusercontent.com/72589844/156509422-5acfe4ad-f866-4c54-a133-f171333e0e59.png)
 

It can be made something similar to this
![Screenshot 2022-03-03 120425](https://user-images.githubusercontent.com/72589844/156509780-d75dfa5f-be21-4882-8fc8-eae1826cfc90.png)


Hope you understand the approach thank you eagerly waiting to be assigned for this project

**Comment by ronitblenz** [comment]
Hey brother @19arnab190201 You are viewing version 1.0 of the website... you have to view the preview link from Dev Branch
https://techsquad-community-website-ci1lflge2-ronitblenz.vercel.app/

**Comment by ronitblenz** [comment]
If still you have something to modify, let me know asap

**Comment by 19arnab190201** [comment]
@ronitblenz ya the latest section what i was initially planning to change is looking good i found a new isssue the Cover page i think it need some modification

**YELLOW PART** - _EXCESS SPACE IN THE TOP  MAKING THE NAV BAR AND COVER PAGE LOOK UNTIDY_ 
**RED PART** - _THIS PART IS NOT ALLIGNED IN THE CENTER AND THE IMAGE ALSO DOSENT MATCHES THE PROJECT I CAN UPDATE IT WILL MORE SUITABLE IMAGE_ 

![TechSquad Community (1)](https://user-images.githubusercontent.com/72589844/156513341-591986f7-f81c-480e-a879-2de496354053.png)

FINALLY ADDING SOME ANNIMATED CONTENT ON THE COVER PAGE TO MAKE IT LOOK MORE ATTRACTIVE

**Comment by ronitblenz** [comment]
> @ronitblenz ya the latest section what i was initially planning to change is looking good i found a new isssue the Cover page i think it need some modification
> 
> **YELLOW PART** - _EXCESS SPACE IN THE TOP  MAKING THE NAV BAR AND COVER PAGE LOOK UNTIDY_ 
> **RED PART** - _THIS PART IS NOT ALLIGNED IN THE CENTER AND THE IMAGE ALSO DOSENT MATCHES THE PROJECT I CAN UPDATE IT WILL MORE SUITABLE IMAGE_ 
> 
> ![TechSquad Community (1)](https://user-images.githubusercontent.com/72589844/156513341-591986f7-f81c-480e-a879-2de496354053.png)
> 
> FINALLY ADDING SOME ANNIMATED CONTENT ON THE COVER PAGE TO MAKE IT LOOK MORE ATTRACTIVE
>  

The yellow denoted portion is currently in progress under an issue...

You can fix the alignment a bit. And
Can you tell me regarding the animation you are planning to do?

**Comment by 19arnab190201** [comment]
@ronitblenz something similar to these 

https://www.sliderrevolution.com/templates/mini-website/?utm_medium=inline-ad&utm_source=animated-website-templates

**Comment by ronitblenz** [comment]
How many days will it take to complete the animation?

**Comment by ronitblenz** [comment]
> Max of 2/3 days

Its looking good, but you shouldn't change the design of the page... and you will work only on this part

![](https://user-images.githubusercontent.com/72589844/156513341-591986f7-f81c-480e-a879-2de496354053.png)

**Comment by ronitblenz** [comment]
Also, you can add some cubes or shapes to add some cherry on top

Assigning you

**Comment by 19arnab190201** [comment]
@ronitblenz Hey, can I also fix the navbar extra spacing because it's not allowing me to work properly on the cover page.

**Comment by ronitblenz** [comment]
😊 sure

**Comment by 19arnab190201** [comment]
@ronitblenz PR done hope u liked it
