### ISSUE TITLE
Attach links in the Quick Links to the given sections of the webpage

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#9]
![image](https://user-images.githubusercontent.com/88646338/155554799-4bcf6953-77a9-47ca-beab-a7f8e75316cb.png)

Link the Resources tag to the resources page and that goes the same for the rest of the tags.

**Comment by ishika1501** [comment]
@JaynouOliver  sir , please assign this to me .

**Comment by ronitblenz** [comment]
You will be assigned on 1st march

**Comment by ronitblenz** [comment]
You can start working on the issue from now on, I will assign you on 1st march, then you can create a PR 
Because you have much time left

**Comment by Pragatii08** [comment]
I can work on it.

**Comment by Kittu22f** [comment]
I can work in it

**Comment by JaynouOliver** [comment]
you can look into some other issues. The assigning of issues happens on a first come first serve basis.

**Comment by JaynouOliver** [comment]
@ishika1501 go for it!
Happy Hacking!

**Comment by HarshKumarChoudary** [comment]
If this level1 task is not over, then please consider me for completing it.

**Comment by Kittu22f** [comment]
Okk
Thank you
And pls tell last date
