### ISSUE TITLE
Create a Pricing Page

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#91]
Assign this to me under GSSoC

### Description

A link to pricing page is mentioned in footer

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by HarshKumarChoudary** [comment]
I would like to contribute to this under GSSOC 22. Please assign it to me.

**Comment by ronitblenz** [comment]
I am Sorry, that pricing link was just a part of dafault footer... We dont have any paid services, everything is free till now.
So, this is not required right now
and yah, thanks for your interest... Meanwhile you can work on other issues or make a new one too after asking me or the mentors.

**Comment by Kumar-laxmi** [comment]
Bro if you don't mind you can reopen this issue and relace the pricing with FAQ page

**Comment by ronitblenz** [comment]
Make a new issue for that

**Comment by Kumar-laxmi** [comment]
ok

**Comment by Kumar-laxmi** [comment]
done created!!
