### ISSUE TITLE
Createa new page for FAQ

### ISSUE THREAD

**Issue by Kumar-laxmi** [Tech-Squad-Community/techsquad-community-website#93]
### Description

The link specified in footer for price can be replaced with 'FAQ' and a new FAQ page can be linked to it

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by ronitblenz** [comment]
I am sorry but my team and mentors decided not to have faq page.. atleast for now... 
Plz watch out other issues and if you have any other ideas in mind... ping me ronitblenz#6939 on discord... after discussion issues can be made

**Comment by Kumar-laxmi** [comment]
ohk bro
