### ISSUE TITLE
Enhancemet : Changing Illustration according to the brand theme color

### ISSUE THREAD

**Issue by akki251** [Tech-Squad-Community/techsquad-community-website#95]
### Description

- This illustration is a bit away from color theme which is shade of blue, hence I will be replacing it.
![image](https://user-images.githubusercontent.com/67007034/156717217-4cf391b7-e5a6-40f3-a8b2-e19fa0a6be02.png)

# New illustration 

![Online friends-rafiki](https://user-images.githubusercontent.com/67007034/156717684-2cac8eb7-9dfc-40b8-9ab1-b7e2b7a2fb8b.png)

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

@r3yc0n1c

**Comment by ronitblenz** [comment]
Woooh... Assigned 🔥
