### ISSUE TITLE
About page can be improved.

### ISSUE THREAD

**Issue by AdnanMuzavor** [Tech-Squad-Community/techsquad-community-website#96]
### Description

About page can be improved by placing member's images in decent card which resemble to cards in home page.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript) of this project.

**Comment by HarshKumarChoudary** [comment]
I'm GSSOC 22 contributor. I would like to work on this issue, please assign it to me. Also please add GSSOC22 label for that. Thanks

**Comment by JaynouOliver** [comment]
Start working @AdnanMuzavor
